version: 2
issues:
  - name: Technical Debt
    description: Address technical debt to improve code maintainability and performance
    title: "[TECHNICAL DEBT] "
    labels: ["technical debt"]
    assignees:
    - ''
    body:
      - type: markdown
        attributes:
          value: |
            **As a** developer  
            **I need** to address technical debt  
            **So that** the codebase is maintainable and performs efficiently  

            **Assumptions:** 
            * Technical debt areas are identified.
            * There is agreement on the best approach to address them.

            **Acceptance Criteria:**
            - [ ] Task 1
            - [ ] Task 2
            - [ ] Task 3
  - name: Chores
    description: Routine maintenance tasks
    title: "Chore: "
    labels: ["chores"]
    assignees:
    - ''
    body:
      - type: markdown
        attributes:
          value: |
            **As a** manager  
            **I need** to oversee routine maintenance tasks  
            **So that** the project remains functional and up to date  

            **Assumptions:** 
            * Routine tasks are clearly defined.
            * Necessary tools and resources are available.

            **Acceptance Criteria:**
            - [ ] Task 1
            - [ ] Task 2
            - [ ] Task 3
  - name: Enhancement
    description: Improve existing functionalities
    title: "Enhancement: "
    labels: ["enhancement"]
    assignees:
    - ''
    body:
      - type: markdown
        attributes:
          value: |
            **As a** developer  
            **I need** to enhance existing functionalities  
            **So that** the system performs better and offers improved features  

            **Assumptions:** 
            * Existing functionalities are identified for enhancement.
            * Clear criteria for improvement are established.

            **Acceptance Criteria:**
            - [ ] Task 1
            - [ ] Task 2
            - [ ] Task 3
  - name: User Stories
    description: Derive insights from data
    title: "Feature: "
    labels: ["feature"]
    assignees:
    - ''
    body:
      - type: markdown
        attributes:
          value: |
            **As an** analyst  
            **I need** to derive insights from data  
            **So that** we can make informed business decisions  

            **Assumptions:** 
            * Data is available and accessible.
            * Analytical tools are set up and ready to use.

            **Acceptance Criteria:**
            - [ ] Task 1
            - [ ] Task 2
            - [ ] Task 3
